# Generated by Django 3.2 on 2023-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('account', '0002_auto_20230410_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='chat.Chat'),
        ),
    ]
