# Generated by Django 3.2 on 2023-04-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
    ]
