# Generated by Django 3.2 on 2023-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=300)),
                ('feedback', models.TextField(default='Путота...')),
                ('stars', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='feedbacks',
            field=models.ManyToManyField(to='account.UserFeedback'),
        ),
    ]
