# Generated by Django 3.2 on 2023-04-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('deadlines', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('photo', models.TextField()),
                ('category', models.ManyToManyField(to='task.TaskCategory')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL)),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
