# Generated by Django 3.2 on 2023-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswer',
            name='comment',
            field=models.TextField(default='Коментарий не отсавлен'),
        ),
    ]
